# Generated by Django 5.2.4 on 2025-10-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='banners/videos/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
