# Generated by Django 5.2.4 on 2025-10-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('youtube_url', models.URLField(help_text='Paste full YouTube link, e.g., https://youtu.be/xyz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
