# Generated by Django 5.2.4 on 2025-10-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contactmessage_delete_brochure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
