# Generated by Django 5.2.4 on 2025-10-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_contactmessage_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default='New Mahavir Tent House', max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=255)),
                ('upi_qr', models.ImageField(blank=True, null=True, upload_to='bank_qr/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
