# Generated by Django 5.2.4 on 2025-10-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_videotestimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YouTubeTestimonial',
        ),
    ]
