# Generated by Django 5.2.4 on 2025-10-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_youtubetestimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videotestimonial',
            old_name='video',
            new_name='video_file',
        ),
        migrations.AddField(
            model_name='videotestimonial',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials_thumbnails/'),
        ),
    ]
