# Generated by Django 5.2.4 on 2025-10-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_video_videotestimonial_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotestimonial',
            name='thumbnail',
        ),
    ]
