# Generated by Django 5.2.4 on 2025-10-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_videotestimonial_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotestimonial',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials_thumbs/'),
        ),
    ]
